services:
    sonata.admin.api_client:
        class: Fnash\ApiKeyBundle\Admin\ApiClientAdmin
        arguments:
            - ~
            - Fnash\ApiKeyBundle\Entity\ApiClient
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Rest API", label: "API Client" }